---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sqlsrv.fullname" . }}
  labels:
    {{- include "sqlsrv.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: sqlsrv
      protocol: TCP
      name: sqlsrv
  selector:
    {{- include "sqlsrv.selectorLabels" . | nindent 4 }}
