replicaCount: 1
workerReplicaCount: 1
schedulerReplicaCount: 1

image:
  repository: ghcr.io/vanegmondgroep/data-sync
  pullPolicy: Always
  tag: "2.x"

imageCredentials:
  registry: ghcr.io
  username: ""
  password: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # cert-manager.io/cluster-issuer: lets-encrypt
  hosts:
    - host: data-sync.vanegmond.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: data-sync-ingress-tls
  #    hosts:
  #      - data-sync.vanegmond.cloud

# Add environment variables from .env.example
environment: {}
  # APP_NAME: "Projecten Database"
