{{- if not .Values.volume.hostPath }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "runtime.fullname" . }}-data
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.volume.storage }}"
{{- end }}
