---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runtime.fullname" . }}-env
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.environment }}
  "{{ $key }}": "{{ $val | toString | b64enc }}"
  {{- end }}
