replicaCount: 1

image:
  repository: ghcr.io/sitepilot/runtime
  pullPolicy: Always
  tag: "8.0"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # cert-manager.io/cluster-issuer: lets-encrypt
  hosts:
    - host: runtime.vanegmond.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: runtime-ingress-tls
  #    hosts:
  #      - runtime.vanegmond.cloud

# Add environment variables from .env.example
environment: {}
  # APP_NAME: "Laravel"

volume:
  hostPath: ""
  storage: 10G
