---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}-env
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.environment }}
  "{{ $key }}": "{{ $val | toString | b64enc }}"
  {{- end }}
