---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailhog.fullname" . }}
  labels:
    {{- include "mailhog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 1025
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    {{- include "mailhog.selectorLabels" . | nindent 4 }}
