---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}-env
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.environment }}
  "{{ $key }}": "{{ $val | toString | b64enc }}"
  {{- end }}
