---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-sync.fullname" . }}-app
  labels:
    {{- include "data-sync.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "data-sync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "data-sync.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "data-sync.fullname" . }}-pull
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          envFrom:
            - secretRef:
                name: {{ include "data-sync.fullname" . }}-env
