---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-sync.fullname" . }}-scheduler
  labels:
    {{- include "data-sync.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "data-sync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "data-sync.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "data-sync.fullname" . }}-pull
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bash", "-c", "cat /www/app/public/config/crontab | crontab - && cron -f"]
          envFrom:
            - secretRef:
                name: {{ include "data-sync.fullname" . }}-env
