---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-sync.fullname" . }}-pull
  labels:
    {{- include "data-sync.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
